name: Style Reformatting

on:
  push:

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Set Up Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install Black & Isort
        run: python -m pip install -U black isort
      - name: Reformat with Black & Isort
        continue-on-error: true
        run: |
          make black-reformat
          make isort-reformat
      - name: Commit Changes
        if: ${{ success() }}
        continue-on-error: true
        run: |
          git config --local committer.email "noreply@github.com"
          git config --local committer.name "GitHub"
          git config --local author.email "${{ github.actor }}@users.noreply.github.com"
          git config --local author.name "{{ github.actor }}"
          git add -A
          git commit -m "Style Reformatting"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}